### PR TITLE
Add base directories

### LINKED ISSUE #11: Setup base directories
## Why
Setup base directories for API projects (controllers, models and so on)

## Acceptance Criteria
- Create base directories for API project following the RFC #10

### PR DESCRIPTION
**Pull request by gutakk**
## What happened 👀
Resolve #11 
 
## Insight 📝
- Add base directories follow the [RFC](https://github.com/nimblehq/gin-templates/issues/10).
- Add basic README and gitignore.

### Testing steps
- Install cookiecutter (you can follow the instruction in README).
- Checkout to this branch.
- Run command `cookiecutter <path to this repo in your local machine>`
- Your new application is created 🎉 .
 
## Proof Of Work 📹
- Create the app named `test-app`
Screen Shot 2564-02-09 at 13 53 29

### CODE REVIEW

**Review by olivierobert — APPROVED** [review]

**Review by sleepylee — APPROVED** [review]

**Review by hoangmirs — APPROVED** [review]
Just a suggestion. Should we change those `.keep` files to `README` files so that we can know the purpose of each folder? 
This is an example of NuxtJS project:
README_md_—_test-nuxt

**Comment by gutakk** [comment]
> Just a suggestion. Should we change those `.keep` files to `README` files so that we can know the purpose of each folder?
> This is an example of NuxtJS project:
> README_md_—_test-nuxt

As Go and Gin are new for us at Nimble, I think this would be helpful for developers.
What do you guys think? @olivierobert @sleepylee @carryall @junan 🤔

**Review by junan — APPROVED** [review]

**Comment by olivierobert** [comment]
@gutakk The Wiki is made for this purpose. I added the basic structure for your use case:
image

The template should only contain the needed files. The wiki is to document the project. 

From the Nuxt JS example, these files link to the official documentation. Also, I feel it would be annoying to have to delete these files each time.

**Review by carryall — APPROVED** [review]

**Comment by gutakk** [comment]
> @gutakk The Wiki is made for this purpose. I added the basic structure for your use case:
> image
> 
> The template should only contain the needed files. The wiki is to document the project.
> 
> From the Nuxt JS example, these files link to the official documentation. Also, I feel it would be annoying to have to delete these files each time.

Added new issue https://github.com/nimblehq/gin-templates/issues/14

**Pull request merged**
